site:
  title: '@dtinth’s documentation site'
  url: https://docs.dt.in.th
  start_page: docs::index.adoc
  robots: allow
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: docs
  - url: https://github.com/dtinth/dtinth.tools-android.git
    branches: main
    start_path: docs
ui:
  bundle:
    url: ./ui-bundle-637d0a7.zip
