site:
  title: '@dtinth’s documentation site'
  url: https://docs.dt.in.th
  start_page: docs::index.adoc
  robots: allow
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: ./ui-bundle-f3a0ace.zip
