= Authoring guide

[#write]
== Writing docs

To develop a documentation in individual project, first create `docs/antora.yml`:

[source,yaml]
----
name: project-name
version: main
title: 'Project name'
----

Then create `modules/ROOT/pages/index.adoc` with the contents.

[#preview]
== Previewing docs

In VS Code, AsciiDoc files can be previewed using the https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc extension]. This gives faster feedback but has lower fidelity. For high fidelity preview, install the development server:

 $ npm install --global dtinth/docs

Then run this script from project root directory:

 $ dtinth-docs-server

Then open http://localhost:9090/ in a web browser. The documentation site will automatically build when files are changed.

.How it works
****
The `dtinth/docs` package bundles Antora and the UI bundle used in `docs.dt.in.th`, and exposes a CLI that starts a preview server, watches for changes and rebuilds the preview site.
****

[#nav]
== Creating a navigation file

Add this to `docs/antora.yml`:

[source,yaml]
----
nav:
- modules/ROOT/nav.adoc
----

Then create `docs/modules/ROOT/nav.adoc`:

[source,asciidoc]
----
* xref:index.adoc[]
----

[#publish]
== Publishing

. Add a new entry to https://docs.google.com/spreadsheets/d/1kFc9bDizrANULuVSUuHYiZENdPzXZpXvuUWlbZbF_uU/edit#gid=0[the docs.dt.in.th spreadsheet on Google Sheets].
. https://github.com/dtinth/docs/actions/workflows/pages.yml[Rebuild the site on GitHub Actions]

== Deploying the documentation site from CLI

For converience, the deployment workflow action can be triggered from the CLI:

 $ dtinth-docs-dev deploy

After committing your changes, you can push and redeploy the site in one go:

 $ git push && dtinth-docs-dev deploy

NOTE: The https://cli.github.com/[GitHub CLI] must be installed.