= docs.dt.in.th

*docs.dt.in.th* builds upon the https://antora.org/[Antora multi-repository documentation site generator] to provide an improved xref:authoring.adoc[authoring workflow] through a custom CLI script, inspired by https://backstage.io/docs/features/techdocs/techdocs-overview[Backstage’s TechDocs].

https://github.com/dtinth/docs[The source code is on GitHub.]

== Easy to author with high fidelity previewing

* By running the `dtinth-docs-dev` command, a project documentation can be previewed in isolation through a local development server.
* The development server automatically rebuilds the documentation whenever a file is changed.
* See more information in xref:authoring.adoc[].

.How it works
****
* The https://docs.antora.org/antora/2.3/playbook/[playbook file] for the project is generated on-the-fly, so documentation is previewed in isolation, but with the same setup that would be used to deploy the site to GitHub Pages.
****

== Easy to add new project documentations

* New documentation can be added to the site by xref:authoring.adoc#publish[adding a new entry in the Google Sheets spreadsheet], so there is no need to fiddle with playbook files.

.Why Antora?
****
* Antora uses https://asciidoc.org/[AsciiDoc], which is more flexible than Markdown. AsciiDoc has been used successfully for big projects, such as https://github.com/elastic/docs[the Elastic stack].
* Antora uses https://asciidoctor.org/[Asciidoctor], which is a https://asciidoc.org/#:~:text=Asciidoctor%20provides%20a,the%20AsciiDoc%20syntax[recommended by AsciiDoc].
* Antora is used to generate https://docs.asciidoctor.org/[Asciidoctor documentation].
****

== Minimize laborious tasks

Building and publishing a documentation site is only part of the whole story. How about social share images? How about SEO? How about analytics? These are things that you have to do each time you set up a new documentation site. Putting documentation together in a single place allows each project documentations to benefit from shared tools.

Social image::
https://github.com/dtinth/personal-puppeteer[personal-puppeteer] is used to generate screenshots for each page, which are then used for social image.
When a documentation page is shared, people can see the contents of the page before clicking on the shared link.
Analytics::
Google Analytics support https://docs.antora.org/antora/2.3/playbook/environment-variables/#:~:text=GOOGLE_ANALYTICS_KEY[comes built-in with Antora through the `GOOGLE_ANALYTICS_KEY` environment variable].

