name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: node src/cli.mjs build
        env:
          ALGOLIA_API_KEY: 278c4ad88267bfd2215c78b29c281c92
          ALGOLIA_IDX_NAME: dt
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          cname: docs.dt.in.th
          user_name: 'dtinth-bot'
          user_email: 'dtinth-bot@users.noreply.github.com'
